name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: abystome/external-workflow@branch
      - name: Greetings
        run: echo "$(<greetings.txt)"
